# UI Control Agent Configuration
agent:
  name: "UI Control Assistant"
  version: "1.0.0"
  description: "AI-powered conversational UI control agent"

# LLM Configuration
llm:
  provider: "openai"
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 1000
  stream: true

# System Prompt Configuration
prompts:
  system: |
    You are a helpful and conversational UI assistant that helps users interact with web applications naturally.
    
    Your role is to:
    - Have natural, friendly conversations with users
    - Understand what users want to do and help them accomplish it
    - Use UI tools to control the interface (navigate, search, interact with elements)
    - Explain what you're doing in a conversational way
    - Ask helpful follow-up questions
    - Remember user preferences and context
    
    When a user asks for something:
    1. Respond naturally and explain what you'll do
    2. Use the appropriate UI tools to execute their request  
    3. Follow up with helpful suggestions or questions
    
    Be conversational like: "Sure! I can help you with that. Let me search for you..."
    Then explain what you found and ask what they'd like to do next.
    
    Always be helpful, proactive, and maintain a natural conversation flow.
    
  user_greeting: |
    Hello! I'm here to help you navigate and interact with this application. 
    I can help you find what you're looking for, navigate to different sections, 
    and complete various tasks. What would you like to do today?

# Memory Configuration
memory:
  enabled: true
  max_history: 10  # Number of conversation turns to remember
  context_window: 4000  # Max tokens for context
  
  # What to remember
  remember:
    - user_preferences
    - search_queries
    - product_interactions
    - cart_activities
    - navigation_patterns

# Tool Configuration
tools:
  ui_tools:
    config_file: "tools.json"  # UI display and interaction tools
    event_format: "ui_event"
    
  backend_tools:
    enabled: true  # Enable backend data tools
    functions:
      - "search_products_data"      # Gets actual search results

# Response Configuration  
responses:
  default_format: "conversational"
  include_suggestions: true
  max_response_length: 500
  
  # UI Event formats
  ui_events:
    navigate:
      type: "navigation"
      parameters: ["page", "category", "filters"]
    
    search:
      type: "product_search"
      parameters: ["query", "filters", "sort_by", "limit"]
      
    cart_action:
      type: "cart_operation"
      parameters: ["action", "product_id", "quantity"]

# Error Handling
error_handling:
  fallback_response: "I apologize, but I encountered an issue. Let me try to help you in a different way."
  retry_attempts: 3
  timeout_seconds: 30 